services:
  - docker
  
script:
  - if [ $TRAVIS_BRANCH != 'master' ]; then sed -i "s|docker-vfb-geppetto|docker-vfb-geppetto:$TRAVIS_BRANCH|g" Dockerfile; fi
  - docker build -t test-image:test .
  - docker run -d --name test test-image:test
  - docker logs test
